version: 0.10-dev{build}

# fetch repository as zip archive
shallow_clone: true

notifications:
- provider: Email
  to:
  - silx-ci@edna-site.org
  subject: '[CI] appveyor'
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true

os:
    - Visual Studio 2015

cache:
    - '%LOCALAPPDATA%\pip\Cache'

environment:
    global:
        WIN_SDK_ROOT: "C:\\Program Files\\Microsoft SDKs\\Windows"
        VENV_BUILD_DIR: "venv_build"
        VENV_TEST_DIR: "venv_test"

    matrix:
        # Python 3.5
        - PYTHON_DIR: "C:\\Python35"
          PYTHON_VERSION: "3.5.10"
          PYTHON_ARCH: "32"

        - PYTHON_DIR: "C:\\Python35-x64"
          PYTHON_VERSION: "3.5.0"
          PYTHON_ARCH: "64"

        # Python 3.6
        - PYTHON_DIR: "C:\\Python36-x64"
          PYTHON_ARCH: "64"

        # Python 3.7
        - PYTHON_DIR: "C:\\Python37"
          PYTHON_ARCH: "32"

        - PYTHON_DIR: "C:\\Python37-x64"
          PYTHON_ARCH: "64"

        # Python 3.8
        - PYTHON_DIR: "C:\\Python38-x64"
          PYTHON_ARCH: "64"    
    


install:
  # Add Python to PATH
  - "SET PATH=%PYTHON_DIR%;%PYTHON_DIR%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"print(tuple.__itemsize__*8)\""

  # Upgrade/install distribution modules
  - "pip install --upgrade setuptools"
  - "python -m pip install --upgrade pip"

  # Install the build and runtime dependencies of the project.
  - "pip install --trusted-host www.silx.org -r ci\\requirements_appveyor.txt"

build_script:
  - "python setup.py build"
  - "python setup.py bdist_wheel bdist_msi"
  - ps: "ls dist"
  # Install the generated wheel package to test it
  - "pip install --pre --find-links dist/  --no-cache-dir --no-index fabio"

test_script:
  # Test the installed package using the project script
  - "python run_tests.py --installed"

  # Move back to the project folder
  - "cd .."

artifacts:
  # Archive the generated wheel package in the ci.appveyor.com build report.
  - path: dist\*

